// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGIuaPQ1_bAmQlNbXfbBEg070mL9ckKLw',
    appId: '1:527595526059:web:dd6d433f937e7e45aaa4ee',
    messagingSenderId: '527595526059',
    projectId: 'libroappdb',
    authDomain: 'libroappdb.firebaseapp.com',
    storageBucket: 'libroappdb.firebasestorage.app',
    measurementId: 'G-M48Z99EEN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuDkxnHKsYrrGczZ0qg_bQ0sLWxiqCRpE',
    appId: '1:527595526059:android:e30c32071813af9eaaa4ee',
    messagingSenderId: '527595526059',
    projectId: 'libroappdb',
    storageBucket: 'libroappdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUgTYtESSg5WQL3Znbqsqyo-EX6f70o6Y',
    appId: '1:527595526059:ios:ca17ccceea271125aaa4ee',
    messagingSenderId: '527595526059',
    projectId: 'libroappdb',
    storageBucket: 'libroappdb.firebasestorage.app',
    iosBundleId: 'com.example.libreriaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUgTYtESSg5WQL3Znbqsqyo-EX6f70o6Y',
    appId: '1:527595526059:ios:ca17ccceea271125aaa4ee',
    messagingSenderId: '527595526059',
    projectId: 'libroappdb',
    storageBucket: 'libroappdb.firebasestorage.app',
    iosBundleId: 'com.example.libreriaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGIuaPQ1_bAmQlNbXfbBEg070mL9ckKLw',
    appId: '1:527595526059:web:592d25b28c567875aaa4ee',
    messagingSenderId: '527595526059',
    projectId: 'libroappdb',
    authDomain: 'libroappdb.firebaseapp.com',
    storageBucket: 'libroappdb.firebasestorage.app',
    measurementId: 'G-YSZ3BRRXVC',
  );
}
